title: QRMR B.V.
logo: /assets/img/cloud_helm.png
description: QRMR stands for QuarteRMasteR. When building clouds, we are the quartermasters helping you get up and running in no-time. Agile, Secure and Compliant.
linkedin_url: https://linkedin.com/company/qrmr
gitlab_url: https://gitlab.com/qrmr
show_downloads: false
google_analytics: UA-99956832-1
theme: jekyll-theme-minimal
